import Test from "@/components/test";
import Head from "next/head";
import { useEffect } from "react";

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Questa è la pagina </div>
      <Test />
    </>
  );
};

export default AboutUs;
